### PR TITLE
update dockerfile: avoid out of memory error while installing pytorch

### PR DESCRIPTION
**Pull request by reshalfahsi**
Hey, I add `--no-cache-dir` flag to avoid out of memory error while installing pytorch in `vortex/dockerfiles/vortex.dockerfile`

### CODE REVIEW

**Comment by triwahyuu** [comment]
can you show me the errors you encounter?

**Comment by reshalfahsi** [comment]
image

There was an issue but resolved by this second commit. Please check it out.

**Comment by triwahyuu** [comment]
I don't have much experience regarding docker container, but I think your last issue was happened because you did not run the docker file inside the repository. This docker file is mostly used for development actually, so you need to actually have the repository in the first place.
cc @alifahrri

**Comment by triwahyuu** [comment]
could you show me your first issue? how can I reproduce it?

**Comment by triwahyuu** [comment]
hi @reshalfahsi, any updates on this issue?

**Comment by triwahyuu** [comment]
I would close this PR as the dockerfile will be heavily updated.

**Pull request closed without merging**
