### PR TITLE
Pytorch Lightning integration

### PR DESCRIPTION
**Pull request by triwahyuu**
## Type of changes

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the new behavior?

-
-
-

## Checklist

- [ ] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have filled the `[Unreleased]` [Changelog](https://github.com/nodefluxio/vortex/blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by alifahrri** [comment]
@triwahyuu I think it's okay if you want to merge this. I'll bring comments or suggestion (if any) to weekly meeting instead, I think it is easier that way

**Comment by triwahyuu** [comment]
@alifahrri this will be a long running PR for everything related to PL integration. could you review the #100?

**Comment by alifahrri** [comment]
> @alifahrri this will be a long running PR for everything related to PL integration. could you review the #100?

ok please wait,

BTW, sorry that I've been out of the loop recently, so this branch will wait until all fixed then it can be merged? I don't know but I think it is better to directly merge to master branch since we agree to undergo major refactor anyway so I think it is expected that feature changes and bugs exist.

And also I think it is better to skip tests for legacy features that make tests fail and expected to be changed rather than leave it the way it is. By doing so I think it will be easier to collaborate

**Comment by alifahrri** [comment]
On skipping tests, actually I have marked some tests so it runs green, just let me know what you think

**Pull request merged**
