### PR TITLE
better user experience

### LINKED ISSUE #16: [FEATURE] Improving CLI parser
**Is your feature request related to a problem? Please describe.**
current CLI description is not helpful enough, e.g. vortex --help lack detailed information

**Describe the solution you'd like**
Follow example of dvc CLI configuration

### PR DESCRIPTION
**Pull request by triwahyuu**
## Type of changes

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

closes #16 

## What is the new behavior?

- change to use `enlighten` progress bar
- add global verbosity level for logger
- better help message

## Checklist

- [x] Unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have filled the `[Unreleased]` [Changelog](https://github.com/nodefluxio/vortex/blob/master/CHANGELOG.md)

## New
- Progress bar on training

image

- help message, use `vortex --help` and `vortex <command> --help` to see

image

image

- new `list` command to list available (and registered) components

image

### CODE REVIEW

**Review by alifahrri — APPROVED** [review]
lgtm

**Comment by triwahyuu** [comment]
oh yeah, I forgot to mention I have also added the `list` command, please check it out. cc @alifahrri @farisais @amajidsinar

**Comment by triwahyuu** [comment]
any more comment guys? @alifahrri @farisais

**Comment by alifahrri** [comment]
> any more comment guys? @alifahrri @farisais

Lgtm

**Pull request merged**
